apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  labels:
    app: backend
data:
  PORT: "3000"
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: bitcoin_db
  POSTGRES_USER: postgres
  REDIS_HOST: redis
  REDIS_PORT: "6379"
