apiVersion: v1
kind: Service
metadata:
  name: redisinsight
  labels:
    app: redisinsight
spec:
  type: LoadBalancer
  ports:
    - port: 5540
      targetPort: 5540
      protocol: TCP
      name: http
  selector:
    app: redisinsight
