apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres
    environment: {{ .Values.environment }}
  annotations:
    "helm.sh/resource-policy": "delete"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.postgres.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
