apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-{{ .Values.namespace }}
  labels:
    app: postgres
    environment: {{ .Values.environment }}
    namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.postgres.storage.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.postgres.storage.storageClassName }}
  hostPath:
    path: /tmp/postgres-data
