{{- if .Values.redisinsight.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: redisinsight
  namespace: {{ .Values.namespace }}
  labels:
    app: redisinsight
    environment: {{ .Values.environment }}
spec:
  type: {{ .Values.redisinsight.service.type }}
  ports:
    - port: {{ .Values.redisinsight.service.port }}
      targetPort: {{ .Values.redisinsight.service.port }}
      protocol: TCP
      name: http
  selector:
    app: redisinsight
{{- end }}
