{{- if .Values.redisinsight.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight
  namespace: {{ .Values.namespace }}
  labels:
    app: redisinsight
    environment: {{ .Values.environment }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisinsight
  template:
    metadata:
      labels:
        app: redisinsight
        environment: {{ .Values.environment }}
    spec:
      containers:
        - name: redisinsight
          image: "{{ .Values.redisinsight.image.repository }}:{{ .Values.redisinsight.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.redisinsight.service.port }}
              name: http
          resources:
            requests:
              memory: {{ .Values.redisinsight.resources.requests.memory }}
              cpu: {{ .Values.redisinsight.resources.requests.cpu }}
            limits:
              memory: {{ .Values.redisinsight.resources.limits.memory }}
              cpu: {{ .Values.redisinsight.resources.limits.cpu }}
          volumeMounts:
            - name: redisinsight-storage
              mountPath: /data
      volumes:
        - name: redisinsight-storage
          emptyDir: {}
{{- end }}
